version: '3'
services:
  wabot:
    image: ghcr.io/talhabalaj/wabot:${TAG}
    restart: always
    environment:
      - MONGO_URL=${MONGO_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - LOG_LEVEL=${LOG_LEVEL}
      - TESTING=${TESTING}
      - IMAGE_EDIT_SERVER_ADDRESS=image_service:50015

  image_service:
    image: ghcr.io/talhabalaj/wabot-image-editing-service:${TAG}
    restart: always
    environment:
      - PORT=50015
