apiVersion: apps/v1
kind: Deployment
metadata:
  name: wabot
spec:
  selector:
    matchLabels:
      app: wabot
  template:
    metadata:
      labels:
        app: wabot
    spec:
      containers:
      - name: wabot
        image: ghcr.io/talhabalaj/wabot:v3.0.0
        env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: mongo-db-url 
                key: url
      restartPolicy: Always
      imagePullSecrets:
      - name: dockerconfigjson-github-com
