# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_editor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12image_editor.proto\"-\n\rGradesRequest\x12\r\n\x05text1\x18\x01 \x01(\t\x12\r\n\x05text2\x18\x02 \x01(\t\"\x1f\n\x0eGradesResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x32:\n\x0bImageEditor\x12+\n\x06Grades\x12\x0e.GradesRequest\x1a\x0f.GradesResponse\"\x00\x62\x06proto3')



_GRADESREQUEST = DESCRIPTOR.message_types_by_name['GradesRequest']
_GRADESRESPONSE = DESCRIPTOR.message_types_by_name['GradesResponse']
GradesRequest = _reflection.GeneratedProtocolMessageType('GradesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GRADESREQUEST,
  '__module__' : 'image_editor_pb2'
  # @@protoc_insertion_point(class_scope:GradesRequest)
  })
_sym_db.RegisterMessage(GradesRequest)

GradesResponse = _reflection.GeneratedProtocolMessageType('GradesResponse', (_message.Message,), {
  'DESCRIPTOR' : _GRADESRESPONSE,
  '__module__' : 'image_editor_pb2'
  # @@protoc_insertion_point(class_scope:GradesResponse)
  })
_sym_db.RegisterMessage(GradesResponse)

_IMAGEEDITOR = DESCRIPTOR.services_by_name['ImageEditor']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GRADESREQUEST._serialized_start=22
  _GRADESREQUEST._serialized_end=67
  _GRADESRESPONSE._serialized_start=69
  _GRADESRESPONSE._serialized_end=100
  _IMAGEEDITOR._serialized_start=102
  _IMAGEEDITOR._serialized_end=160
# @@protoc_insertion_point(module_scope)
