# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_editor_pb2 as image__editor__pb2


class ImageEditorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Grades = channel.unary_unary(
                '/ImageEditor/Grades',
                request_serializer=image__editor__pb2.GradesRequest.SerializeToString,
                response_deserializer=image__editor__pb2.GradesResponse.FromString,
                )


class ImageEditorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Grades(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageEditorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Grades': grpc.unary_unary_rpc_method_handler(
                    servicer.Grades,
                    request_deserializer=image__editor__pb2.GradesRequest.FromString,
                    response_serializer=image__editor__pb2.GradesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImageEditor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageEditor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Grades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ImageEditor/Grades',
            image__editor__pb2.GradesRequest.SerializeToString,
            image__editor__pb2.GradesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
