name: Docker Image CI

on: 
  push:
    tags: 
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/talhabalaj/wabot:${{ steps.get_version.outputs.VERSION }} --tag ghcr.io/talhabalaj/wabot:latest
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the Docker image to GitHub Container Registry (versioned)
      run: docker push ghcr.io/talhabalaj/wabot:${{ steps.get_version.outputs.VERSION }}
    
    - name: Push the Docker image to GitHub Container Registry (latest)
      run: docker push ghcr.io/talhabalaj/wabot:latest
